## Main Ansible playbook that will call all Roles
---
- name: Test Connection to Hosts
  hosts: all
  tasks:
    action: ping

- name: Mef_eLine Tests
  hosts: all
  roles:
    - python
    - create_vlan
    - test_one
    - delete_vlan
    - delete_evc


