## Main Ansible playbook that will call all Roles
---
- name: Test Connection to Hosts
  hosts: all
  tasks:

#    - name: Generate KEY
#      openssh_keypair:
#        path: /tmp/id_ssh_rsa
#        force: True
#
#    - name: Add KEY to Hosts
#      authorized_key:
#        user: ansible_user
#        state: present
#        key: "{{ lookup('file', 'id_rsa.pub') }}"
#        path: /tmp/id_ssh_rsa

    - action:
        name: ping

- name: Mef_eLine Tests
  hosts: all
  roles:
    - python
    - create_vlan
    - create_evc
    - test_one
    - delete_vlan
    - delete_evc
    - cleaning


- name: Delete KEY
  hosts: all
  tasks:
    - name: Delete KEY from Hosts
      authorized_key:
        user: ansible_user
        state: absent
        key: "{{ lookup('file', 'id_rsa.pub') }}"
        path: /tmp/id_ssh_rsa