## Main Ansible playbook that will call all Roles
---
- name: Test Connection to Hosts
  hosts: all
  tasks:
    - name: Generate KEY
      openssh_keypair:
        path: /root/
        force: True
    - name: ADD KEY to Hosts
      authorized_key:
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

    - ping:

- name: Mef_eLine Tests
  hosts: all
  roles:
    - python
    - create_vlan
    - create_evc
    - test_one
    - delete_vlan
    - delete_evc
    - cleaning


