---
- name: Start Test 1
  hosts: all
  remote_user: amlight

  tasks:
    - name: Ping the server
      action: ping

    - name: Install Python
      raw: test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal) || (yum -y install python libselinux-python)

    - name: Install requests module
      command: pip3 install requests


    - name: Create and Activate Vlan
      shell: ip link add link "{{ net }}" name "{{ net }}"."{{ item|int }}" type vlan id "{{ item|int }}"
      with_sequence: start="{{ start }}" end="{{ end }}"

    - name: Setting Vlan
      command: ip addr add 10.0."{{ item|int }}"."{{ inet }}"/24 brd 10.0."{{ item|int }}".255 dev "{{ net }}.{{ item|int }}"
      with_sequence: start="{{ start }}" end="{{ end }}"

    - name: Activating Vlan
      shell: ip link set dev "{{ net }}.{{ item|int }}" up
      with_sequence: start="{{ start }}" end="{{ end }}"

    - name: Copy Test 1 Scrip
      copy: src=py_files/evc_request.py dest=/tmp/  owner=root mode=755

    - name: Running Test 1 Script
      command: python3 /tmp/evc_request.py "{{ item }}" create_evc
      with_sequence: start="{{ start}}" end="{{ end }}"




#################### Removing Test ###################
    - name: Delete the EVC
      command: python3 /usr/local/src/evc_request.py "{{ item }}" delete_evc
      with_sequence: start="{{ start}}" end="{{ end }}"

    - name: Deactivate Vlan
      command: ip link set dev "{{ net }}"."{{ item|int }}" down
      with_sequence: start="{{ start }}" end="{{ end }}"

    - name: Remove Vlan
      command: ip link delete "{{ net }}"."{{ item|int}}"
      with_sequence: start="{{ start }}" end="{{ end }}"
