---
#- name: Install Python in CentOS 7
#  yum:
#    name: "python"
#    state: latest
- name: Install SCL
  command: yum install centos-release-scl

- name: Install install Python 3.6 SCL
  command: yum install rh-python36

- name: Activate Python 3.6 SCL Bash
  command: scl enable rh-python36 bash