---
- name: Install  epel-release
  yum:
    name: "epel-release"

- name: Install SCL
  yum:
    name: "centos-release-scl"
    state: present

- name: Install install Python 3.6 SCL
  yum:
    name: "rh-python36"
    state: present

- name: Install pip
  yum:
    name: "python-pip"


- name: Installing requests module
  pip:
    name: "requests"
    executable: /opt/rh/rh-python36/root/usr/bin/pip3

- name: Installing pythonping module
  pip:
    name: "pythonping"
    executable: pip3

#- name: Activate Python 3.6 SCL Bash
#  command: scl enable rh-python36 bash