---
- name: Install  epel-release
  yum:
    name: "epel-release"

- name: Install SCL
  yum:
    name: "centos-release-scl"
    state: present

- name: Install install Python 3.6 SCL
  yum:
    name: "rh-python36"
    state: present

- name: Install pip
  yum:
    name: "python-pip"

- name: Install Virtualenv
  pip:
    name: "virtualenv"
    executable: /opt/rh/rh-python36/root/usr/bin/pip3

- name: Install setuptools
  pip:
    name: "setuptools"
    executable: /opt/rh/rh-python36/root/usr/bin/pip3

- name: Create Virtual Enviroment
  pip:
    name: "python3"
    state: present
    virtualenv: /tmp/mef_eline_python
    virtualenv_command: /opt/rh/rh-python36/root/usr/bin/python3 -m venv
#    virtualenv_python: python3
#    virtualenv_site_packages: yes


- name: Installing requests module
  pip:
    name: "requests"
    virtualenv: /tmp/mef_eline_python
    virtualenv_site_packages: yes
#    virtualenv_command:
#    executable: /opt/rh/rh-python36/root/usr/bin/pip

- name: Installing pythonping module
  pip:
    name: "pythonping"
    virtualenv: /tmp/mef_eline_python
    virtualenv_site_packages: yes
#    virtualenv_command: /opt/rh/rh-python36/root/usr/bin/pip

#- name: Activate Python 3.6 SCL Bash
#  command: scl enable rh-python36 bash