---
- name: Install  epel-release
  yum:
    name: "epel-release"

- name: Install SCL
  yum:
    name: "centos-release-scl"
    state: present

- name: Install install Python 3.6 SCL
  yum:
    name: "rh-python36"
    state: present

- name: Install pip
  yum:
    name: "python-pip"


- name: Installing requests module
  pip:
    name: "requests"

- name: Installing pythonping module
  pip:
    name: "pythonping"

#- name: Activate Python 3.6 SCL Bash
#  command: scl enable rh-python36 bash