---
- name: Install SCL
  yum:
    name: "centos-release-scl"
    state: present

- name: Install install Python 3.6 SCL
  yum:
    name: "rh-python36"

- name: Activate Python 3.6 SCL Bash
  command: scl enable rh-python36 bash