---
#- name: Installing Python
#  raw: test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal) || ( yum install centos-release-scl && yum install rh-python36)
- import_tasks: centos.yml
  when: ansible_distribution == 'CentOS'
- import_tasks: ubuntu.yml.yml
  when: ansible_distribution == 'Ubuntu'