---
#- name: Installing requests module
#  command: /opt/rh/rh-python36/root/usr/bin/pip3 install requests
#- name: Installing requests module
#  pip:
#    name: "requests"


- name: Running Create EVC Script
  command: "{{ role_path }}"/files/evc_request.py "{{ controller_addr }}" "{{ controller_port }}" "{{ item }}" create_evc
  args:
    chdir: /tmp/
    executable: /opt/rh/rh-python36/root/usr/bin/python3
    creates: circuits.txt
  with_sequence: start="{{ start}}" end="{{ end }}"