---
#- name: Copy EVC Scrip
#  copy:
#    src: "{{ role_path }}/files/evc_request.py"
#    dest: /tmp/evc_request.py

- name: Creating EVCs
  hosts: local
  tasks:
    - include: centos.yml
      when: ansible_distribution == 'CentOS'

    - include: ubuntu.yml
      when: ansible_distribution == 'Ubuntu'

#- name: Delete Test 1 Scrip
#  file:
#    path: /tmp/evc_request.py
#    state: absent