---
#- name: Installing requests module
#  pip:
#    name: "requests"
#    executable: pip3


- name: Running Create EVC Script
  shell: "{{ role_path }}/files/evc_request.py {{ controller_addr }} {{ controller_port }} {{ item }} create_evc"
  args:
    chdir: /tmp/
    executable: python3
    creates: circuits.txt
  with_sequence: start="{{ start}}" end="{{ end }}"