---
- name: Installing requests module
  pip:
    name: "requests"


- name: Running Create EVC Script
  command: python3 /tmp/evc_request.py "{{ item }}" create_evc
  with_sequence: start="{{ start}}" end="{{ end }}"