---
- name: Delete the EVC
  command: python3 /usr/local/src/evc_request.py "{{ item }}" delete_evc
  with_sequence: start="{{ start}}" end="{{ end }}"

- name: Deactivate Vlan
  command: ip link set dev "{{ net }}"."{{ item|int }}" down
  with_sequence: start="{{ start }}" end="{{ end }}"

- name: Remove Vlan
  command: ip link delete "{{ net }}"."{{ item|int}}"
  with_sequence: start="{{ start }}" end="{{ end }}"

- name: Delete Test 1 Scrip
  file:
    path: /tmp/evc_request.py
    state: absent