---
- name: Running Create EVC Script
  shell: /opt/rh/rh-python36/root/usr/bin/python3 /tmp/evc_request.py {{ controller_addr }} {{ controller_port }} {{ item }} delete_evc
    args:
      chdir: /tmp/
      #    executable: /opt/rh/rh-python36/root/usr/bin/python3
      deletes: circuits.txt
    with_sequence: start="{{ start}}" end="{{ end }}"