---
- name: Create and Activate Vlan
  raw: ip link add link "{{ net }}" name "{{ net }}"."{{ item }}" action vlan id "{{ item }}"
  with_sequence: start="{{ start }}" end="{{ end }}"

- name: Setting Vlan
  raw: ip addr add 10.0."{{ item }}"."{{ inet }}"/24 brd 10.0."{{ item }}".255 dev "{{ net }}.{{ item }}"
  with_sequence: start="{{ start }}" end="{{ end }}"

- name: Activating Vlan
  raw: ip link set dev "{{ net }}.{{ item }}" up
  with_sequence: start="{{ start }}" end="{{ end }}"