---

- name: Install vconfig (without 'args').
  command: yum install vconfig.x86_64

- name: Create Vlan
  command: vconfig add "{{net}}" "{{item|int}}" up
  with_sequence: start="{{start}}" end="{{end}}"

- name: Config Vlan
  command: ifconfig "{{net}}.{{item|int}}" 10.0."{{item|int}}.{{inet|int}}"/24 up
  with_sequence: start="{{start}}" end="{{end}}"
