---
- name: Install vconfig
  yum:
    name: vconfig

#- name: Create Vlan
#  command: "./vconfig add {{ net }} {{ item|int }} up"
##  args:
##    executable: ./
##
#  with_sequence: start="{{start }}" end="{{ end }}"
#
#- name: Activating Vlan
#  command: "./ifconfig {{ net }}.{{ item|int }} 10.0.{{ item|int }}.{{ inet|int }}/24 up"
##  args:
##    executable: ./
#  with_sequence: start="{{ start }}" end="{{ end }}"


#- name: Install vconfig
#  shell: yum install vconfig.x86_64
#  args:
#    executable: /bin/bash

- name: Install vconfig (without 'args').
  command: yum install vconfig.x86_64


#- name: install needed network manager libs
#  package:
#    name:
#      - NetworkManager-glib
#      - nm-connection-editor
#      - libsemanage-python
#      - policycoreutils-python
#    state: present
#
#- name: Add VxLan
#  nmcli:
#    type: vlan
#    comm_name: "{{ net }}.{{ item|int }}"
#    ifname: "{{ net }}"
#    vlan_id: "{{item}}"
##    ip4: "10.0.{{ item }}.{{ inet }}/24"
#    state: present
#  with_sequence: start="{{start}}" end="{{end}}"
#
#- name: Optionally, at the same time specify IPv6 addresses for the device
#  nmcli:
#    conn_name: "{{ net }}.{{ item|int }}"
#    ifname: "{{ net }}"
#    type: ethernet
#    ip4: "10.0.{{ item }}.{{ inet }}/24"
#    state: present
#  with_sequence: start="{{start}}" end="{{end}}"

#- name: Create and Activate Vlan
#  raw: "ip link add link {{ net }} name {{ net }}.{{ item|int }} action vlan id {{ item|int }}"
#  args:
#    executable: /bin/bash
#  with_sequence: start="{{ start }}" end="{{ end }}"
#
#- name: Setting Vlan
#  shell: "ip addr add 10.0.{{ item }}.{{ inet }}/24 brd 10.0.{{ item|int }}.255 dev {{ net }}.{{ item }}"
#  args:
#    executable: /bin/bash
#
#  with_sequence: start="{{ start }}" end="{{ end }}"
#
#- name: Activating Vlan
#  raw: "ip link set dev {{ net }}.{{ item }} up"
#  with_sequence: start="{{ start }}" end="{{ end }}"