---
- name: Create and Activate Vlan
  shell: "ip link add link {{ net }} name {{ net }}.{{ item|int }} action vlan id {{ item|int }}"
  with_sequence: start="{{ start }}" end="{{ end }}"

- name: Setting Vlan
  shell: "ip addr add 10.0.{{ item }}.{{ inet }}/24 brd 10.0.{{ item|int }}.255 dev {{ net }}.{{ item }}"
  with_sequence: start="{{ start }}" end="{{ end }}"

- name: Activating Vlan
  raw: "ip link set dev {{ net }}.{{ item }} up"
  with_sequence: start="{{ start }}" end="{{ end }}"